name: editorconfig
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: editorconfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: editorconfig # will run `yarn editorconfig` command
