name: ESLint
# Слушаем события  пул реквест в мастер и пуш в мастер
on:
  pull_request:
  push:
    branches:
      - master
# Работы
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      # checkout@v2 - изготовленный гитхабом чекаутит на отдельный вновь созданный сервер
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: borales/actions-yarn@v1.22.5
        with:
          node-version: ${{ matrix.node-version }}
        with:
          cmd: install # will run `yarn install` command
        with:
          cmd: eslint # will run `yarn eslint` command
