name: ESlint
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v1.22.5
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v1.22.5
        with:
          cmd: eslint # will run `yarn eslint` command
